### ISSUE TITLE
Configurable prefix

### ISSUE THREAD

**Issue by sethfitz** [openimagerynetwork/oin-meta-generator#13]
In #10, I started to explain the layout of my terrain buckets. In addition to the `4326/` prefix, I also have a `3857/` prefix that contains derived data (for tiling purposes), both reprojected and resampled per zoom.  Since that's not intended directly for publishing purposes, I'd like to limit the prefix that the tool uses to list data to be processed.

**Comment by jflasher** [comment]
I like the idea of including a prefix, looking over the documentation, it looks like this should be achievable with the `Delimiter` and `Prefix` properties, but I wasn't having any luck getting it to work on a test bucket with a folder structure. If you can get it to work on your bucket, I'll definitely check it out.

**Comment by sethfitz** [comment]
This works with `S3_BUCKET_PREFIX=3857/z12/` (the bucket I'm using is `s3://cgiar-csi-srtm.openterrain.org` if you'd like to experiment):

``` diff
diff --git i/index.js w/index.js
index ea67fed..c7742e5 100644
--- i/index.js
+++ w/index.js
@@ -44,7 +44,8 @@ console.info('Successfully connected to S3 bucket, now retrieving data.');

 var params = {
   s3Params: {
-    Bucket: process.env.S3_BUCKET_NAME /* required */
+    Bucket: process.env.S3_BUCKET_NAME, /* required */
+    Prefix: process.env.S3_BUCKET_PREFIX || ''
   }
 };

```

**Comment by jflasher** [comment]
Hmm, now I'm stumped. I was trying to same thing. I have a folder in the bucket called `foo` with an image inside of it. I set the prefix to `foo/` and I'm getting nothing. Interestingly, when I'm viewing S3 via the web and go into the folder, it adds `prefix=foo/` to the url and the image shows up correctly. I thought it might have been a permissions problem but everything seems to be world viewable/readable.

**Comment by sethfitz** [comment]
Huh.  Try it with this environment (it just worked for me):

``` bash
S3_BUCKET_NAME=cgiar-csi-srtm.openterrain.org
S3_BUCKET_PREFIX=3857/z12/
```

**Comment by jflasher** [comment]
Confirmed that works. I'm going to go ahead and merge in the change and assume this is somehow a permission error on my bucket, but I'm not sure why.
